"use client"

import {ThemeUIProvider} from "theme-ui"
import "../lib/fclConfig"
import theme from "../lib/theme"
import {GoogleAnalytics} from "nextjs-google-analytics"
import "./fonts.css"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <ThemeUIProvider theme={theme}>
          <GoogleAnalytics />
          {children}
        </ThemeUIProvider>
      </body>
    </html>
  );
}
